### ISSUE TITLE
klte(-common) camera broken/doesn't work on cm14

### ISSUE THREAD

**Issue by nine7nine** [TheMuppets/proprietary_vendor_samsung#862]
Hi,

I've built cm14 from source for sm-g900w8 (kltecan/eur). Camera no longer works... Previously, cm13 builds were fine - however, beyond my backup, I can't build cm13 to see if the problem was the merge of the MM blobs in klte-common... Unfortunately, my SSD drive isn't big enough to handle having 2 AOSP trees and I've ditched cm13... However, I have a hunch that the camera not working has to do with the blobs being updated and not tested across devices... 

...well, and possibly poor maintenance of the klte's kernel. https://github.com/CyanogenMod/android_kernel_samsung_klte/tree/cm-14.0 ...It might be missing something needed, idk... it hasn't had the greatest maintainership over the last bunch of months and there is still a lot of stuff missing; seccomp-bpf; which would be nice for minijails/Nougat, fstack-protector-strong, gcc-5+ support, fix for samsung's types-mismatch, usb-fast-charge, no updates/fixes from LTS or google's 3.4 kernels, etc...

I guess I will have to grab the blobs off a stock image and see if I can get the camera working on my own.. right now, it just complains that camera 0 doesn't exist or can't be opened, when trying to use snap/camera app...

**Comment by javelinanddart** [comment]
....Um what?
In addition to the fact that taking pictures works fine, our kernel is also in fine shape, and I'm not sure what you're going on about. also, cm14 is *far* from release ready on klte and even if it was nightlies, this isn't where to open regression reports, we have a place for that, and it's called jira.

**Comment by nine7nine** [comment]
Well, cm14 may be far from release (on klte and in general), but essentially all of the main/most important stuff is working fine on klte, with the camera exception for me. Regardless of the claim that 'taking pictures works fine'; It does *not* on my sm900-w8. So it may work on *some* Galaxy s5 models/devices, but currently *not* on the sm-900w8.

Secondly, the kernel may be in okay shape, but not great shape for Nougat. It works, but is lacking support for security features like seccomp-bpf (sandboxing), breaks compilation on gcc5+ or linaro toolchains and is missing a lot of other bits/fixes for linux-3.4... third, my point on the kernel wasn't to bash anyone... Just pointing out that it is lacking in a few ways and has been slow to pull in samsung code drops and/or backport relevant features and fixes...

Regardless, I apologize for the noise - I will likely just sort it out myself.

**Comment by haggertk** [comment]
cm-14.0 for klte doesn't *really* exist, it's alpha at best. Furthermore, this repository is not a cyanogenmod repository. And if it were, CM does not accept issue reports through github. This is probably the least productive means possible of providing CM feedback. If you want changes to CM, submit changes to CM gerrit.
